/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view;

import app.controller.MatriculaController;
import app.controller.DocenteController;
import java.awt.Component;
import java.util.List;
import java.util.Map;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CBrayan
 */
public   class Matricula extends javax.swing.JPanel {

    /**
     * Creates new form Matriculas
     */
    public Matricula() {
        initComponents();
        matricula();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatriculas = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 153));

        tblMatriculas.setBackground(new java.awt.Color(255, 255, 153));
        tblMatriculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO ALUMNO", "ALUMNO", "DOCENTE", "CURSO", "FECHA INICIO", "FECHA FINAL"
            }
        ));
        jScrollPane1.setViewportView(tblMatriculas);

        btnBuscar.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtCodigo.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel7.setText("CÓDIGO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        for (Component c : this.getComponents()) {
            if (c instanceof JTextField) {
                JTextField t = (JTextField) c;
                t.setText("");
            }
        }
    }

    public void matricula() {
        MatriculaController controller = new MatriculaController();
        List<Map<String, Object>> matriculas = controller.mostrarMatriculas();
        DefaultTableModel tabla;
        tabla = (DefaultTableModel) tblMatriculas.getModel();
        tabla.setRowCount(0);
        for (Map<String, Object> r : matriculas) {
            Object[] rowData = {
                r.get("codigoalumno"),
                r.get("alumno"),
                r.get("docente"),
                r.get("curso"),
                r.get("fechainicio"),
                r.get("fechafin"),
            };
            tabla.addRow(rowData);
        }

    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String codigo = txtCodigo.getText();
        MatriculaController controller = new MatriculaController();
        List<Map<String, Object>> matriculas = controller.mostrarMatriculas(codigo);
        DefaultTableModel tabla;
        tabla = (DefaultTableModel) tblMatriculas.getModel();
        tabla.setRowCount(0);
        for (Map<String, Object> r : matriculas) {
            Object[] rowData = {
                r.get("codigoalumno"),
                r.get("alumno"),
                r.get("docente"),
                r.get("curso"),
                r.get("fechainicio"),
                r.get("fechafin"),
            };
            tabla.addRow(rowData);
        }
        limpiar();
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMatriculas;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
