/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.app12.view;

import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.egcc.app12.controller.AlumnoController;
import pe.egcc.app12.model.Alumno;
import pe.egcc.app12.service.AlumnoService;
import pe.egcc.app12.service.AppService;

/**
 *
 * @author Docente
 */
public class AlumnoConsultarView extends javax.swing.JInternalFrame {

  /**
   * Creates new form AlumnoConsultarView
   */
  public AlumnoConsultarView() {
    initComponents();
  }
private void llenarCodAlum() {
        // Obtener periodos
        AlumnoService alumnoService=new AlumnoService();
        java.util.List<String> codAlumno= alumnoService.leerCodigoAlumno();

        // llenar el combo
        cboCodAlumno.removeAllItems();
        for (String s : codAlumno) {
            cboCodAlumno.addItem(s);
        }
        cboCodAlumno.setSelectedIndex(-1);

    }
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboCodAlumno = new javax.swing.JComboBox<String>();
        btnConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaRes = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnLlenar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CONSULTAR ALUMNOS");

        cboCodAlumno.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        cboCodAlumno.setForeground(new java.awt.Color(255, 102, 51));
        cboCodAlumno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCodAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCodAlumnoActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 102, 51));
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        txaRes.setColumns(20);
        txaRes.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        txaRes.setRows(5);
        jScrollPane1.setViewportView(txaRes);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("Codigo :");

        btnLlenar.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        btnLlenar.setForeground(new java.awt.Color(255, 102, 51));
        btnLlenar.setText("LLenar ");
        btnLlenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(cboCodAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLlenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboCodAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLlenar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCodAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCodAlumnoActionPerformed
        // Verificar periodo seleccionado
        int index = cboCodAlumno.getSelectedIndex();
        if (index == -1) {
            return;
        }
        // Obtener periodo seleccionado
        String codigo = cboCodAlumno.getSelectedItem().toString();
    }//GEN-LAST:event_cboCodAlumnoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // Dato

        String codigo = cboCodAlumno.getSelectedItem().toString();
        //PROCESO
        AlumnoService alumnoService = new AlumnoService();
        List<Map<String, Object>> lista = alumnoService.mostrarDatosAlumno(codigo);

        // Reporte
        for (Map<String, Object> r : lista) {
            String fila = "";
            fila += r.get("idalumno") + "\t";
            fila += r.get("apealumno") + "\t";
            fila += r.get("nomalumno") + "\t";
            fila += r.get("diralumno") + "\t";
            fila += r.get("telalumno") + "\t";
            fila += r.get("emailalumno");

            String mensaje = "ID \t APELLIDO \t NOMBRE \t DIRECCIÓN \t TELEFONO \t EMAIL \n";
            txaRes.setText(mensaje + fila);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnLlenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlenarActionPerformed
        llenarCodAlum();
    }//GEN-LAST:event_btnLlenarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLlenar;
    private javax.swing.JComboBox<String> cboCodAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaRes;
    // End of variables declaration//GEN-END:variables
}
