package pe.egcc.app12.view;

import java.awt.Dimension;
import java.util.GregorianCalendar;
import javax.swing.JInternalFrame;
import pe.egcc.app12.model.Empleado;
import pe.egcc.app12.util.Session;

public class MainView extends javax.swing.JFrame {

  public MainView() {
    initComponents();
    establecerTitulo();
    Reloj hilo=new Reloj(hora);
        hilo.start();
        fecha();
  }
  
  private void establecerTitulo(){
    Empleado bean = (Empleado) Session.get("usuario");
    String titulo =  "EDUTEC APP [Usuario: ";
    titulo += bean.getApellido() + ", ";
    titulo += bean.getNombre() + "]";
    this.setTitle(titulo);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuArchivoSalir = new javax.swing.JMenuItem();
        menuProfesor = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuAlumno = new javax.swing.JMenu();
        menuAlumnoConsultar = new javax.swing.JMenuItem();
        menuAlumnoCrear = new javax.swing.JMenuItem();
        menuEmpleado = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuProcesos = new javax.swing.JMenu();
        ConsultaCiclo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuTarifa = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(686, 452));

        desktopPane.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        jLabel1.setText("Fecha:");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(360, 10, 36, 17);

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        jLabel2.setText("Hora:");
        desktopPane.add(jLabel2);
        jLabel2.setBounds(550, 10, 31, 17);

        fecha.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        desktopPane.add(fecha);
        fecha.setBounds(400, 10, 140, 20);

        hora.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        desktopPane.add(hora);
        hora.setBounds(600, 10, 70, 20);

        menuArchivo.setText("Sistema");

        menuArchivoSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuArchivoSalir.setText("Cerrar Sesión");
        menuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuArchivoSalir);

        menuBar.add(menuArchivo);

        menuProfesor.setText("Profesor");

        jMenuItem3.setText("Registrar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuProfesor.add(jMenuItem3);

        menuBar.add(menuProfesor);

        menuAlumno.setText("Alumno");

        menuAlumnoConsultar.setText("Consultar");
        menuAlumnoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlumnoConsultarActionPerformed(evt);
            }
        });
        menuAlumno.add(menuAlumnoConsultar);

        menuAlumnoCrear.setText("Registrar");
        menuAlumnoCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlumnoCrearActionPerformed(evt);
            }
        });
        menuAlumno.add(menuAlumnoCrear);

        menuBar.add(menuAlumno);

        menuEmpleado.setText("Empleado");

        jMenuItem5.setText("Registrar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuEmpleado.add(jMenuItem5);

        menuBar.add(menuEmpleado);

        menuProcesos.setText("Ciclo");

        ConsultaCiclo.setText("Consultar");
        ConsultaCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaCicloActionPerformed(evt);
            }
        });
        menuProcesos.add(ConsultaCiclo);

        jMenuItem1.setText("Registrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuProcesos.add(jMenuItem1);

        menuBar.add(menuProcesos);

        menuTarifa.setText("Tarifa");

        jMenuItem4.setText("Consultar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuTarifa.add(jMenuItem4);

        jMenuItem6.setText("Registrar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuTarifa.add(jMenuItem6);

        menuBar.add(menuTarifa);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void menuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoSalirActionPerformed
    LogonView lb= new LogonView(this, rootPaneCheckingEnabled);
    lb.show(true);
    this.hide();
    
  }//GEN-LAST:event_menuArchivoSalirActionPerformed

  private void menuAlumnoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlumnoConsultarActionPerformed
  JInternalFrame view = new AlumnoConsultarView();
  desktopPane.add(view);
        view.setVisible(true);
        view.show();
  }//GEN-LAST:event_menuAlumnoConsultarActionPerformed

  private void menuAlumnoCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlumnoCrearActionPerformed
 JInternalFrame view = new AlumnoCrearView();
 desktopPane.add(view);
        view.setVisible(true);
        view.show();
  }//GEN-LAST:event_menuAlumnoCrearActionPerformed

    private void ConsultaCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaCicloActionPerformed
        JInternalFrame view = new ConsultarCicloView();
        desktopPane.add(view);
        view.setVisible(true);
        view.show();
    }//GEN-LAST:event_ConsultaCicloActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
   JInternalFrame view = new CrearCicloView();
   desktopPane.add(view);
        view.setVisible(true);
        view.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JInternalFrame view = new TarifaConsultarView();
        desktopPane.add(view);
        view.setVisible(true);
        view.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JInternalFrame view = new TarifaCrearView();
        desktopPane.add(view);
        view.setVisible(true);
        view.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JInternalFrame view = new EmpleadoCrearrView();
        desktopPane.add(view);
        view.setVisible(true);
        view.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JInternalFrame view = new ProfesorCrearView();
        desktopPane.add(view);
        view.setVisible(true);
        view.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainView().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConsultaCiclo;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu menuAlumno;
    private javax.swing.JMenuItem menuAlumnoConsultar;
    private javax.swing.JMenuItem menuAlumnoCrear;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuArchivoSalir;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEmpleado;
    private javax.swing.JMenu menuProcesos;
    private javax.swing.JMenu menuProfesor;
    private javax.swing.JMenu menuTarifa;
    // End of variables declaration//GEN-END:variables
public void fecha() {
        String f=Fecha();
        fecha.setText(f);
        
    }
public String Fecha() {
        GregorianCalendar fecha=new GregorianCalendar();
    int dia =fecha.get(fecha.DAY_OF_MONTH );
    int mes =fecha.get(fecha.MONTH );
    int año =fecha.get(fecha.YEAR );
    String mifecha=String.valueOf(dia)+"/"+nombre(mes)+"/"+String.valueOf(año);
    return mifecha;
    }
public String nombre(int mes) {
        switch(mes){
             case 0:return"Enero";
             case 1:return"Febrero";
             case 2:return"Marzo";
             case 3:return"Abril";
             case 4:return"Mayo";
             case 5:return"Junio";
             case 6:return"Julio";
             case 7:return"Agosto";
             case 8:return"Septiembre";
             case 9:return"Octubre";
             case 10:return"Noviembre";
             case 11:return"Diciembre";     
    }
     return"Error";     
    }
}
