/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view;

import app.controller.CursoNuevoController;
import com.toedter.calendar.JDateChooser;
import java.util.Date;
import app.model.Ciclo;
import app.controller.CicloController;
import app.model.Curso;
import java.awt.Component;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CBrayan
 */
public class CicloNuevo extends javax.swing.JPanel {

    /**
     * Creates new form CicloN
     */
    public CicloNuevo() {
        initComponents();
        ciclos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCiclos = new javax.swing.JTable();
        dateInicio = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dateFinal = new com.toedter.calendar.JDateChooser();
        btnGuardar = new javax.swing.JButton();

        tblCiclos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CICLO", "FECHA INCIO", "FECHA FINAL"
            }
        ));
        jScrollPane1.setViewportView(tblCiclos);

        jLabel7.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel7.setText("FECHA INICIO:");

        jLabel8.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel8.setText("FECHA FINAL:");

        btnGuardar.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(dateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(dateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dateInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addComponent(dateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            Ciclo ciclo = cicloNuevo();
            CicloController controller = new CicloController();
            controller.generarCiclo(ciclo);
            String reporte = "CICLO: " + ciclo.getCodigo();
            ciclos();
            JOptionPane.showMessageDialog(this, reporte, "CICLO REGISTRADO", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR);
        }
        limpiar();
    }//GEN-LAST:event_btnGuardarActionPerformed
    public void ciclos(){
        CicloController controller = new CicloController();
        List<Map<String, Object>> cursos = controller.Ciclo();
        DefaultTableModel tabla;
        tabla = (DefaultTableModel) tblCiclos.getModel();
        tabla.setRowCount(0);
        for(Map<String, Object> r : cursos){
            Object[] rowData = {
                r.get("ciclo"),
                r.get("fechainicio"),
                r.get("fechafinal"),
            };
              tabla.addRow(rowData);     
        }
    }
    public Ciclo cicloNuevo() {
        java.sql.Date fechainicio = fechaSql(dateInicio);
        java.sql.Date fechafinal = fechaSql(dateFinal);
        Ciclo bean = new Ciclo("No recuerdo :v",fechainicio,fechafinal);
        return bean;
    }

    public java.sql.Date fechaSql(JDateChooser date) {
        Date fecha = date.getDate();
        long d = fecha.getTime();
        java.sql.Date fechaSQL = new java.sql.Date(d);
        return fechaSQL;
    }
    public void limpiar(){
        for (Component c : this.getComponents()) {
            if (c instanceof JDateChooser) {
                JDateChooser t = (JDateChooser) c;
                t.setDate(null);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private com.toedter.calendar.JDateChooser dateFinal;
    private com.toedter.calendar.JDateChooser dateInicio;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCiclos;
    // End of variables declaration//GEN-END:variables
}
